---

# see https://arduino.github.io/arduino-cli/1.0/configuration/#configuration-keys

board_manager:
  additional_urls:
    -
      # ⚠️ If this value is updated here, it MUST also be updated in `config.mk`
      "https://espressif.github.io/arduino-esp32/package_esp32_index.json"

directories:
  data: "./.arduino/data"
  downloads: "./.arduino/downloads"
  user: "./.arduino/user"

library:
  enable_unsafe_install: true

locale: "en_US.UTF-8"

logging:
  format: text

metrics:
  enabled: false

sketch:
  always_export_binaries: true

updater:
  enable_notification: false
